data:
  params:
    batch_size: 5
    num_workers: 8
    train:
      params:
        size: 256
        training_images_list_file: /home/student/andrewheschl/Documents/Datasets/ClassificationDataset/results/Dataset_large_421/fold_0/2024_09_16_14_42_291096/train_files.txt
      target: taming.data.custom.CustomTrain
    validation:
      params:
        size: 256
        test_images_list_file: /home/student/andrewheschl/Documents/Datasets/ClassificationDataset/results/Dataset_large_421/fold_0/2024_09_16_14_42_291096/val_files.txt
      target: taming.data.custom.CustomTest
  target: main.DataModuleFromConfig
model:
  base_learning_rate: 4.5e-06
  params:
    ddconfig:
      attn_resolutions:
      - 16
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      double_z: false
      dropout: 0.0
      in_channels: 3
      num_res_blocks: 2
      out_ch: 3
      resolution: 256
      z_channels: 256
    embed_dim: 256
    lossconfig:
      params:
        codebook_weight: 1.0
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 10000
        disc_weight: 0.8
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
    n_embed: 1024
  target: taming.models.vqgan.VQModel
